// Agent Build Pack — raw copy-paste prompt fuel for external agent models
// (Arena.ai Agent Mode, ChatGPT, Claude). The agent writes the book;
// Ghostforge stays the organizer and keeper of series canon.

export type PackBook = {
  id: number; title: string; genre: string; kind: string; premise: string;
  audience: string; tone: string; style: string; pov: string; tense: string;
  target_words: number; pen_name?: string | null;
  series_title?: string | null; series_number?: number | null;
  plan?: { beats: string[]; thesis: string; claims: string[]; approved: boolean; approvedAt: string | null } | null;
};
export type PackChapter = { idx: number; title: string; summary: string; words: number };
export type PackChar = { name: string; role: string; description: string; arc: string };
export type PackPrev = {
  series_number: number | null; title: string; premise: string;
  logline: string; chapterTitles: string[];
};

export function buildAgentPack(
  book: PackBook, chapters: PackChapter[], characters: PackChar[], prev: PackPrev[],
  opts: { build?: 'serial' | 'full' } = {},
): string {
  const full = opts.build === 'full';
  const L: string[] = [];
  const isLit = /litrpg|gamelit/i.test(book.genre);
  const inSeries = !!book.series_title;
  const drafted = chapters.filter((c) => c.words > 0).length;

  L.push('================================================================================');
  L.push(`AGENT BUILD PACK — "${book.title}"`);
  L.push('Generated by Ghostforge. Paste everything below the PASTE LINE into an AI agent');
  L.push('(Arena.ai Agent Mode recommended) and it will write this book for you.');
  if (full) L.push('BUILD MODE: FULL BOOK — the agent writes the entire book back-to-back.');
  L.push('Keep this pack — generate one per book and the series stays in tact.');
  L.push('================================================================================');
  L.push('');
  L.push('------------------------- PASTE BELOW THIS LINE -------------------------');
  L.push('');
  L.push('# ROLE');
  L.push('You are my ghostwriting agent. Write the book specified below to a publishable,');
  L.push('for-sale standard. Continuity beats cleverness: when in doubt, stay consistent with');
  L.push('this bible. Never ask me to "provide more detail" — make strong fitting choices and');
  L.push('list every assumption at the end of each chapter under a short NOTE header.');
  L.push('');
  if (inSeries) {
    L.push('# SERIES BIBLE — KEEP THE SERIES IN TACT');
    L.push(`Series: "${book.series_title}" · This book: #${book.series_number ?? '?'} "${book.title}"${book.pen_name ? ` · Pen name: ${book.pen_name}` : ''}`);
    L.push('');
    if (prev.length) {
      L.push('## Earlier books — ESTABLISHED CANON. Do not contradict anything below.');
      for (const p of prev) {
        L.push(`### Book ${p.series_number ?? '?'}: "${p.title}"`);
        if (p.premise) L.push(`Premise: ${p.premise}`);
        if (p.logline) L.push(`Logline: ${p.logline}`);
        if (p.chapterTitles.length) {
          const shown = p.chapterTitles.slice(0, 60);
          L.push(`Chapters written: ${shown.map((t, i) => `${i + 1}. ${t}`).join(' · ')}${p.chapterTitles.length > 60 ? ` · …+${p.chapterTitles.length - 60} more` : ''}`);
        }
        L.push('');
      }
    } else {
      L.push('This is the FIRST book of the series: you are establishing canon. Record every');
      L.push('named person, place, artifact, rule, and date you invent — later books must match.');
      L.push('');
    }
    L.push('## Continuity rules');
    L.push('1. Same world, same history, same rules as earlier books. No silent retcons — ever.');
    L.push('2. Returning characters keep their voice, abilities, relationships, and fates.');
    L.push('3. If a good idea conflicts with canon, STOP and flag it in the chapter NOTE instead of forcing it.');
    L.push('4. Track every NEW named element you invent and report it in the final SERIES BIBLE UPDATE.');
    L.push('');
  } else {
    L.push('# SERIES STATUS: STANDALONE');
    L.push('No series — but stay strictly consistent within this book (names, timeline, rules).');
    L.push('');
  }
  L.push('# THIS BOOK — SPEC');
  L.push(`- Working title: "${book.title}"`);
  L.push(`- Genre: ${book.genre} · Kind: ${book.kind}`);
  if (book.audience) L.push(`- Audience: ${book.audience}`);
  if (book.tone) L.push(`- Tone: ${book.tone}`);
  if (book.style) L.push(`- Voice target — write in a style like: ${book.style}`);
  if (book.kind === 'fiction') L.push(`- POV: ${book.pov} · Tense: ${book.tense}`);
  L.push(`- Target length: ~${book.target_words.toLocaleString('en-US')} words${chapters.length ? ` across ${chapters.length} planned chapters` : ''}${drafted ? ` (${drafted} already drafted elsewhere — match their quality bar)` : ''}`);
  L.push('');
  L.push('# PREMISE');
  L.push(book.premise || '(No premise recorded — work from the title, genre, and chapter plan.)');
  L.push('');
  const plan = book.plan ?? null;
  const approved = !!plan?.approved;
  const stamp = approved
    ? `Status: APPROVED by the author${plan?.approvedAt ? ` on ${plan.approvedAt.slice(0, 10)}` : ''} — follow this plan exactly. Do not restructure, rename, or reorder without being asked.`
    : 'Status: DRAFT plan — not yet approved. Follow it, but flag structural concerns before Chapter 1.';
  if (book.kind === 'fiction') {
    L.push('# PLOT STRUCTURE');
    L.push(stamp);
    if (plan && plan.beats.length) {
      plan.beats.forEach((bt, i) => L.push(`${i + 1}. ${bt}`));
    } else {
      L.push('(No story beats recorded — derive the arc from the premise and chapter plan, and state it before Chapter 1.)');
    }
    L.push('');
  } else {
    L.push('# THESIS & CORE CLAIMS');
    L.push(stamp);
    L.push(`Thesis: ${plan?.thesis || book.premise || '(none recorded)'}`);
    if (plan && plan.claims.length) {
      L.push('Claims this book must defend with evidence:');
      plan.claims.forEach((cl, i) => L.push(`${i + 1}. ${cl}`));
    }
    L.push('');
    L.push('# NONFICTION HONESTY RULES — NEVER FALSIFY ANYTHING, EVER');
    L.push('1. Never invent, fabricate, or embellish any fact, statistic, date, quote, study, person, event, or source. No exceptions.');
    L.push('2. Only state claims supported by real knowledge. If unsure about a detail, omit it or mark it [VERIFY] — never assert it.');
    L.push('3. Never invent citations. Every factual claim must trace to a real, checkable source.');
    L.push('4. End EVERY chapter with a "Sources to check" list so the author can verify each key claim.');
    L.push('5. If the plan asks for evidence that cannot be verified, say what KIND of source is needed instead of faking it.');
    L.push('');
  }
  L.push('# CAST — ESTABLISHED (reuse exactly: same names, same roles, same voices)');
  if (characters.length) {
    for (const c of characters) L.push(`- ${c.name} — ${c.role}: ${c.description}${c.arc ? ` Arc: ${c.arc}` : ''}`);
  } else if (full) {
    L.push('(No cast recorded — invent a tight cast, list it in 10 lines or fewer, then begin Chapter 1 in the same response.)');
  } else {
    L.push('(No cast recorded — invent a tight cast FIRST and list it for approval before Chapter 1.)');
  }
  L.push('');
  L.push('# CHAPTER PLAN — WRITE EVERY CHAPTER IN FULL PROSE');
  if (chapters.length) {
    const per = Math.round(book.target_words / Math.max(1, chapters.length));
    chapters.forEach((c, i) => L.push(`${i + 1}. "${c.title}" — ${c.summary || '(no summary — invent beats that serve the premise and bible)'}${full ? ` (~${per.toLocaleString('en-US')} words)` : ''}`));
  } else if (full) {
    const n = Math.max(8, Math.min(48, Math.round(book.target_words / 1500)));
    L.push(`No chapter plan exists. State a numbered plan of ~${n} chapters for a`);
    L.push(`~${book.target_words.toLocaleString('en-US')}-word book in 20 lines or fewer, then BEGIN CHAPTER 1`);
    L.push('IN THE SAME RESPONSE. Do not wait for approval.');
  } else {
    const n = Math.max(8, Math.min(48, Math.round(book.target_words / 1500)));
    L.push(`No chapter plan exists. FIRST reply with a numbered plan of ~${n} chapters for a`);
    L.push(`~${book.target_words.toLocaleString('en-US')}-word book and WAIT for approval. Only then start Chapter 1.`);
  }
  L.push('');
  if (isLit) {
    L.push('# LITRPG SYSTEM RULES — NUMBERS ARE CANON');
    L.push('This is a LitRPG: game mechanics are part of the fiction and readers WILL audit them.');
    L.push('1. Keep a hidden LEDGER of every stat block, level, skill, title, item, and number shown.');
    L.push('2. Never contradict the ledger: no retroactive stat changes, no forgotten skills, no fuzzy math.');
    L.push('3. Show progression on screen: levels, loot, and unlocks must be earned in-scene, not summarized.');
    L.push('4. Format system messages consistently (bracketed blocks work well) and keep them skimmable — story first, screens second.');
    L.push('5. End the book with the full LEDGER so the next book in the series inherits exact numbers.');
    L.push('');
  }
  L.push('# HOUSE STYLE');
  L.push('- Complete scenes with action, dialogue, and sensory detail. No summaries where scenes belong.');
  L.push('- No meta-commentary, no placeholders, no "as an AI", no recaps of the instructions.');
  L.push('- Blank line between paragraphs. End every chapter with momentum into the next.');
  L.push('');
  if (full) {
    L.push('# OUTPUT CONTRACT — FULL BOOK BUILD');
    L.push('1. Deliver the COMPLETE book in this session: every chapter in order, back to back.');
    L.push('2. Do not stop for approval between chapters and do not ask me to say "next" —');
    L.push('   keep going until the final chapter is done.');
    L.push('3. Format: `# Chapter N: Title` on its own line, then the full prose, then a blank');
    L.push('   line before the next chapter heading.');
    L.push('4. If you hit response-length limits, end with the line CONTINUED on its own, then');
    L.push('   resume with the next chapter in your following response — unprompted.');
    L.push('5. After the final chapter, deliver the FINAL TALLY + SERIES BIBLE UPDATE below.');
    L.push('   Always deliver it. Never end the book without it.');
    L.push('');
    L.push('# FINAL TALLY + SERIES BIBLE UPDATE (after the last chapter)');
    L.push('1. Word count per chapter, then the book total.');
    L.push('2. Assumptions you made along the way (short list).');
    L.push('3. Every new canon fact future books must honor: characters, places, rules,');
    L.push('   numbers — and the full LEDGER if this is a LitRPG.');
    L.push('');
  } else {
    L.push('# OUTPUT CONTRACT — FOLLOW EXACTLY');
    L.push('1. Deliver ONE chapter per response, in order, starting with Chapter 1.');
    L.push('2. Format: `# Chapter N: Title` on its own line, then the full prose.');
    L.push('3. End each chapter with `(Word count: N)` on its own line, then a short NOTE');
    L.push('   listing: assumptions made + new canon facts introduced (names, rules, numbers).');
    L.push('4. Then STOP and wait for me to say "next". Do not run ahead.');
    L.push('5. After the final chapter, deliver a SERIES BIBLE UPDATE: every new character,');
    L.push('   place, rule, and number future books must honor.');
    L.push('');
  }
  L.push('# CONTINUITY CHECKLIST — VERIFY SILENTLY BEFORE EVERY CHAPTER');
  L.push('- [ ] Names, places, and titles match the bible and earlier chapters');
  L.push('- [ ] Timeline and character knowledge states are consistent');
  if (isLit) L.push('- [ ] Every stat, level, skill, and item matches the LEDGER');
  if (inSeries) L.push('- [ ] Nothing contradicts the earlier books above');
  if (book.kind === 'nonfiction') L.push('- [ ] Every claim is honest; uncertain points marked [VERIFY]; sources listed');
  L.push('- [ ] The chapter hits every beat in its plan line');
  L.push('');
  L.push('(End of Agent Build Pack.)');
  return L.join('\n');
}
